### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by laurelnaiad** [teropa/harmonics-explorer#1]
Hi @teropa ,

This is a great demo of a few different things. Thank you for sharing. I was wondering if you'd be willing to license it for reuse? MIT perhaps? ;) I'm particularly interested in your hmr implementation, which seems nice and clean. 

If not, no worries, you've already taught me something, so thank you.

Cheers,
Daphne

**Comment by teropa** [comment]
Definitely all good for reuse. The project is ISC licensed, as per the `package.json`. I've also added it to the README now.

**Comment by laurelnaiad** [comment]
Thank you! (Readme is great b/c I don't know if our lawyers read package.json files :) )
